<?xml version="1.0" encoding="utf-8"?>
<Database Name="PWAS_DB" Class="PWASDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=&quot;C:\Documents and Settings\RolandoV\My Documents\PWAS\PWAS_Site\PWAS_Site\App_Data\PWAS_DB.mdf&quot;;Integrated Security=True;User Instance=True" SettingsObjectName="PWAS.Model.Properties.Settings" SettingsPropertyName="PWAS_DBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="roleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="role_name" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="role_desc" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Role_RolePermission" Member="RolePermissions" OtherKey="roleID" Type="RolePermission" />
      <Association Name="Role_User" Member="Users" OtherKey="roleID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.RolePermission" Member="RolePermissions">
    <Type Name="RolePermission">
      <Column Name="permissionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="roleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="object" Type="System.String" DbType="NChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="obj_update" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="obj_view" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="obj_create" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="obj_delete" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Role_RolePermission" Member="Role" ThisKey="roleID" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderHistory" Member="OrderHistories">
    <Type Name="OrderHistory">
      <Column Name="orderId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="statusId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="modifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Status_OrderHistory" Member="Status" ThisKey="statusId" Type="Status" IsForeignKey="true" />
      <Association Name="Order_OrderHistory" Member="Order" ThisKey="orderId" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PrintRun" Member="PrintRuns">
    <Type Name="PrintRun">
      <Column Name="runID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="height" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="width" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stock_finish" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="stock_weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="run_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="run_status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Association Name="PrintRun_Order" Member="Orders" OtherKey="runID" Type="Order" />
      <Association Name="Status_PrintRun" Member="Status" ThisKey="run_status" Type="Status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Status" Member="Status">
    <Type Name="Status">
      <Column Name="statusId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="statusName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Status_OrderHistory" Member="OrderHistories" OtherKey="statusId" Type="OrderHistory" />
      <Association Name="Status_PrintRun" Member="PrintRuns" OtherKey="run_status" Type="PrintRun" />
      <Association Name="Status_Order" Member="Orders" OtherKey="currentStatus" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="company" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="homePhone" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="otherPhone" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="s_address1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="s_address2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="s_city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="s_state" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="s_zip" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="cc_num" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="cc_type" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="exp_date" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="cc_scode" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="cc_nameOnCard" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="b_address1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="b_address2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="b_city" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="b_state" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="b_zip" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="roleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="true" />
      <Association Name="User_Order" Member="Orders" OtherKey="userID" Type="Order" />
      <Association Name="Role_User" Member="Role" ThisKey="roleID" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="orderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="runID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="job_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="width" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="height" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stock_finish" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="stock_weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="two_sided" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="folded" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ship" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="currentStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="Order_OrderHistory" Member="OrderHistories" OtherKey="orderId" Type="OrderHistory" />
      <Association Name="PrintRun_Order" Member="PrintRun" ThisKey="runID" Type="PrintRun" IsForeignKey="true" />
      <Association Name="Status_Order" Member="Status" ThisKey="currentStatus" Type="Status" IsForeignKey="true" />
      <Association Name="User_Order" Member="User" ThisKey="userID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>